	INFO:root:Program started
INFO:root:function execution started
INFO:root:function executed well: return value:230
WARNING:root:USer entered alphnumeric value
INFO:root:list initiated:[10, 20, 30, 40, 50, 60, 70, 80, 90]
INFO:root:Try block initiated
ERROR:root:Error:ValueError("invalid literal for int() with base 10: '123ert'",)
Traceback (most recent call last):
  File "./log/log1.py", line 19, in <module>
    value=int(value)
ValueError: invalid literal for int() with base 10: '123ert'
INFO:root:Program ended

.....................................
2016-07-19 07:52:14,652,INFO:Program started
2016-07-19 07:52:14,656,INFO:function execution started
2016-07-19 07:52:14,659,INFO:function executed well: return value:230
2016-07-19 07:52:17,102,INFO:list initiated:[10, 20, 30, 40, 50, 60, 70, 80, 90]
2016-07-19 07:52:17,103,INFO:Try block initiated
2016-07-19 07:52:17,103,INFO:Try block executed well
2016-07-19 07:52:17,104,INFO:Program ended
2016-07-19 07:55:50,272,WARNING:USer entered alphnumeric value
2016-07-19 07:55:50,273,ERROR:Error:ValueError("invalid literal for int() with base 10: 'wer456'",)
Traceback (most recent call last):
  File "./log/log1.py", line 20, in <module>
    value=int(value)
ValueError: invalid literal for int() with base 10: 'wer456'
..................................

2016-07-19 07:56:07,279,WARNING:USer entered alphnumeric value
2016-07-19 07:56:07,282,ERROR:Error:ValueError("invalid literal for int() with base 10: 'wer45'",)
Traceback (most recent call last):
  File "./log/log1.py", line 20, in <module>
    value=int(value)
ValueError: invalid literal for int() with base 10: 'wer45'
